[package]
name = "wellen-binding"
version = "0.1.0"
edition = "2024"

[lib]
crate-type=["cdylib"]

[patch.crates-io]
fst-reader = { git="https://github.com/Simre1/fst-reader.git"}

[dependencies]
wellen="0.15.0"
